"on":
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
name: Deploy to syst
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply
      env:
        PORTER_CLUSTER: "1123"
        PORTER_DEPLOYMENT_TARGET_ID: 8c66c29d-83d1-4af1-8a80-e5fbf78b367c
        PORTER_HOST: https://cloud.porter.run
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_PROJECT: "1210"
        PORTER_REPO_NAME: ${{ github.event.repository.name }}
        PORTER_STACK_NAME: syst
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1210_1123 }}
